server:
  port: 8080

file:
  root: .

spring:
  mvc:
    servlet:
      load-on-startup: 0
  security:
    user:
      name: admin
      password: password
      roles: ADMIN

logging:
  level:
    root: info
  file:
    path: /var/log/java/video-list/
